### ISSUE TITLE
[question]:  Is your documentation on the website out of date? Or are the User methods still in Beta after 7 months?

### ISSUE THREAD

**Issue by selected-pixel-jameson** [OneSignal/onesignal-node-api#79]
### How can we help?

The mobile SDK's which support the user model were released at least 7 months ago. Yet, when I look at the documentation on the website it stats that the Back-End SDK's for this functionality are in Beta and should not be used. Is this actually the case? The repository makes no mention of it. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by shnabz** [comment]
I've followed the docs for the JS SDK, shell, and rest api and none of them work.

**Comment by iAmWillShepherd** [comment]
You can go ahead and use the latest beta SDK for User Model. 

The truth is that these will remain in beta until closer to the official deprecation of the old Player Model SDKs. The documentation for each SDK exists in their respective repos; however, since all SDKs provide the same API, you can view [this doc](https://documentation.onesignal.com/docs/backend-sdk-reference) for high-level details of each function. We're actively working on improving these docs from the current auto-generated ones.
